window_upstream: 60
window_downstream: 30
weights:
  alpha: 1.0
  beta: 1.0
temperature:
  initial: 1.0
  decay: 0.995
ga:
  population_size: 32
  generations: 40
  mutation_rate: 0.05
  tournament_size: 3
output:
  sequence: dna
  allow_rna: true
